// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon;

  Cylon = require('cylon');

  Cylon.robot({
    connections: [
      {
        name: 'leapmotion',
        adaptor: 'leapmotion',
        port: '127.0.0.1:6437'
      }, {
        name: 'skynet',
        adaptor: 'skynet',
        uuid: "0675b9d1-9b7e-11e3-af21-030ff142869f",
        token: "yr2oi19yyspmbo6rcgkp7gov5i2j4i"
      }
    ],
    device: {
      name: 'leapmotion',
      driver: 'leapmotion',
      connection: 'leapmotion'
    },
    led: function(status) {
      console.log(status);
      return this.skynet.message({
        "devices": ["67f040c1-9bf8-11e3-af21-030ff142869f"],
        "message": {
          'red': status
        }
      });
    },
    work: function(my) {
      this.hand = false;
      my.leapmotion.on('frame', (function(_this) {
        return function(frame) {
          if (frame.hands.length > 0) {
            return _this.hand = true;
          } else {
            return _this.hand = false;
          }
        };
      })(this));
      return every(1..seconds(), (function(_this) {
        return function() {
          if (_this.hand === true) {
            return my.led('on');
          } else {
            return my.led('off');
          }
        };
      })(this));
    }
  }).start();

}).call(this);
