// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon, Travis, travis;

  Cylon = require('cylon');

  Travis = require('travis-ci');

  travis = new Travis({
    version: '2.0.0'
  });

  Cylon.robot({
    connection: {
      name: 'digispark',
      adaptor: 'digispark'
    },
    devices: [
      {
        name: 'red',
        driver: 'led',
        pin: 0
      }, {
        name: 'green',
        driver: 'led',
        pin: 1
      }, {
        name: 'blue',
        driver: 'led',
        pin: 2
      }
    ],
    resetLeds: (function(_this) {
      return function(me) {
        me.blue.turnOff();
        me.red.turnOff();
        return me.green.turnOff();
      };
    })(this),
    checkTravis: (function(_this) {
      return function(me) {
        var name, user;
        user = "hybridgroup";
        //name = "cylon";
        name = "broken-arrow";
        console.log("Checking repo " + user + "/" + name);
        me.blue.turnOn();
        return travis.repos({
          owner_name: user,
          name: name
        }, function(err, res) {
          if (res.repo) {
            me.resetLeds(me);
            switch (res.repo.last_build_state) {
              case 'passed':
                return me.green.turnOn();
              case 'failed':
                return me.red.turnOn();
              default:
                return me.blue.turnOn();
            }
          } else {
            return me.blue.turnOn();
          }
        });
      };
    })(this),
    work: function(me) {
      me.resetLeds(me);
      me.checkTravis(me);
      return every(10..seconds(), function() {
        me.resetLeds(me);
        return me.checkTravis(me);
      });
    }
  }).start();

}).call(this);
