// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon;

  Cylon = require('cylon');

  Cylon.robot({
    connection: {
      name: 'ardrone',
      adaptor: 'ardrone',
      port: '192.168.1.1'
    },
    device: {
      name: 'drone',
      driver: 'ardrone'
    },
    work: function(my) {
      my.drone.takeoff();
      after(10..seconds(), function() {
        return my.drone.land();
      });
      return after(15..seconds(), function() {
        return my.drone.stop();
      });
    }
  }).start();

}).call(this);
