// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon;

  Cylon = require('cylon');

  Cylon.robot({
    connection: {
      name: 'arduino',
      adaptor: 'firmata',
      port: '/dev/ttyACM0'
    },
    devices: [
      {
        name: 'led',
        driver: 'led',
        pin: 13
      }, {
        name: 'button',
        driver: 'button',
        pin: 2
      }
    ],
    work: function(my) {
      return my.button.on('push', function() {
        return my.led.toggle();
      });
    }
  }).start();

}).call(this);
