// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon;

  Cylon = require('cylon');

  Cylon.robot({
    connections: [
      {
        name: 'beaglebone',
        adaptor: 'beaglebone'
      }, {
        name: 'skynet',
        adaptor: 'skynet',
        uuid: "67f040c1-9bf8-11e3-af21-030ff142869f",
        token: "8bf0jls222tvs4iw6e94wa09qm8ia4i"
      }
    ],
    device: {
      name: 'led',
      driver: 'led',
      pin: 'P9_12',
      connection: 'beaglebone'
    },
    work: function(my) {
      Logger.info("connected...");
      return my.connections['skynet'].on('message', function(channel, data) {
        console.log(data);
        if (data.red === 'on') {
          console.log("red on request received from skynet");
          return my.led.turnOn();
        } else if (data.red === 'off') {
          console.log("red off request received from skynet");
          return my.led.turnOff();
        }
      });
    }
  }).start();

}).call(this);
