// Generated by CoffeeScript 1.7.1
(function() {
  var Cylon;

  Cylon = require('cylon');

  Cylon.robot({
    connection: {
      name: 'sphero',
      adaptor: 'sphero',
      port: '/dev/rfcomm0'
    },
    device: {
      name: 'sphero',
      driver: 'sphero'
    },
    work: function(me) {
      return every(1..second(), function() {
        return me.sphero.roll(60, Math.floor(Math.random() * 360));
      });
    }
  }).start();

}).call(this);
